platform :ios, '5.1'
pod 'InAppSettingsKit', '~> 1.1'
pod 'Reachability',  		'~> 3.1.0'
pod 'AFNetworking', 		'~> 1.2.1'
pod 'JASidePanels', 		'~> 1.3.1'
pod 'Facebook-iOS-SDK', '~> 3.5.1'
pod 'SVProgressHUD', 		'~> 0.9'
